### ISSUE TITLE
README about how to use this

### ISSUE THREAD

**Issue by ramonsmits** [Run1e/WindowSwitcher#3]
I cloned the repo but I don't have any AHK experience. I thought that this script switches between apps of the same type via `` ALT+` `` unfortunately is is not working on my Win 10 box (v1909).

I see the following config entry for `Key` but I'm not sure how to interpret this.

    Key := "^!I"

https://github.com/Run1e/WindowSwitcher/blob/master/WindowSwitcher.ahk#L8

Any help appreciated as this seems like a very useful script.

**Comment by Run1e** [comment]
`^!I` is AHK notation for a hotkey binding. This specific one means CTRL+ALT+P

Read more about that here: https://www.autohotkey.com/docs/Hotkeys.htm

To use this, download AutoHotkey https://github.com/Lexikos/AutoHotkey_L/releases

Then run the .ahk script in this repo and press CTRL+ALT+P, or rebind it.

**Comment by ramonsmits** [comment]
Provided a README in this PR: https://github.com/Run1e/WindowSwitcher/pull/4
