### ISSUE TITLE
Enhancement: Close window when window loses focus or give focus if open and don't close

### ISSUE THREAD

**Issue by ramonsmits** [Run1e/WindowSwitcher#5]
Currently the window remains open if it loses focus. It is not always obvious that the window is still open and then requires pressing the shortcut key twice.

a. If window loses focus, close window.
b. If window loses focus, remain open but if shortcut is pressed don't close window but give it focus.

Unfortunately I'm a total AHK n00b to implement this.

**Comment by Run1e** [comment]
Fixed in 4e2530100a372f701e478f36668aa682ed9adcda - closing issue
